# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Required for the Disks feature
Vagrant.require_version ">= 2.2.8"
ENV['VAGRANT_EXPERIMENTAL'] = 'disks'
MEMORY = 2048
# Box metadata location and box name
BOX_NAME = "ferventcoder/win2008r2-x64-nocm"
DISKSİZE = "16GB"
PROVIDER = "virtualbox"

# define hostname
NAME = "windows-2008"
if ! File.exists?('./resources/NDP452-KB2901907-x86-x64-AllOS-ENU.exe')
  puts '.Net 4.5.2 installer could not be found!'
  puts "Please run:\n  wget http://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901907-x86-x64-AllOS-ENU.exe"
  exit 1
end

if ! File.exists?('./resources/Octopus.Tentacle.2.6.0.778-x64.msi')
  puts 'Octopus Tentacle installer could not be found!'
  puts "Please run:\n  wget http://download.octopusdeploy.com/octopus/Octopus.Tentacle.2.6.0.778-x64.msi"
  exit 1
end

PASSWD = 123456

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = BOX_NAME
  config.vm.define NAME
  config.vm.guest = :windows
  config.vm.communicator = "winrm"


  #  config.ssh.insert_key = false
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    config.vm.provision 'shell', inline: 'net user vagrant #{PASSWD}'

  #  config.vm.provision 'shell', inline: 'echo "vagrant:cancan123" | chpasswd'


  config.vm.provision :shell, path: "scripts/install-iis.cmd"
  config.vm.provision :shell, path: "scripts/delete-default-iis-website.ps1"
  config.vm.provision :shell, path: "scripts/install-dot-net.ps1"
  config.vm.provision :shell, path: "scripts/install-dot-net-45.cmd"
  config.vm.provision :shell, path: "scripts/install-octopus-tentacle.cmd"
  config.vm.provision :shell, path: "scripts/configure-octopus-tentacle.cmd"

  config.vm.boot_timeout = 600
  config.vm.hostname = NAME + ".vagrant.vm"



  config.vm.provider PROVIDER do |v, override|
    v.memory = MEMORY
    v.name = NAME
    override.vm.disk :disk, size: DISKSİZE, name: 'docker_storage'
  end


end
